name: Deploy image to registry

env: 
  SERVICE_NAME: agentic-ai-website
  PROJECT_ID: powerful-star-471309-u8
  DOCKER_IMAGE_URL: us-east1-docker.pkg.dev/powerful-star-471309-u8/agent-website/agent

on:
  push:
    branches:
      - master

jobs:
  dockerize-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Google Cloud Auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
          project_id: ${{ env.PROJECT_ID }}

      - name: Build and Push Docker Image
        run: |
            docker build -t ${{ env.DOCKER_IMAGE_URL}}:latest -f Dockerfile .
            gcloud auth configure-docker us-east1-docker.pkg.dev
            docker push ${{ env.DOCKER_IMAGE_URL }}:latest
      - name: Deploy to Cloud Run
        run: |
            echo SERVICE_NAME $SERVICE_NAME
            gcloud run deploy $SERVICE_NAME \
              --image ${{ env.DOCKER_IMAGE_URL}}:latest \
              --platform managed \
              --region us-east1 \
              --max-instances 2 \
              --timeout 3m \
              --port 8080 \
              --no-allow-unauthenticated \
              --memory 2Gi \
              --cpu 2 \
              --set-secrets="\
              OPENAI_API_KEY=OPENAI_API_KEY:latest,\
              LANGSMITH_API_KEY=LANGSMITH_API_KEY:latest,\
              SERPER_API_KEY=SERPER_API_KEY:latest,\
              LANGSMITH_PROJECT=LANGSMITH_PROJECT:latest" \
              --set-env-vars="\
              LANGSMITH_TRACING=true,\
              LANGSMITH_ENDPOINT=https://api.smith.langchain.com"
